FROM node:22-alpine3.19

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY ./package*.json ./

COPY ./tsconfig.json ./

COPY ./jest.config.js ./

RUN npm ci

COPY ./src /usr/src/app/src

COPY ./tests /usr/src/app/tests

USER node